// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ExamenP2_62453
{
	public partial class CustomTableViewCell : UITableViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CustomTableViewCell));
        public string Tweet
        {
            get => TxtTweet.Text;
            set => TxtTweet.Text = value;
        }
        public string ReTweet
        {
            get => TxtRetweets.Text;
            set => TxtRetweets.Text = value;
        }
        public string Fav
        {
            get => TxtFavs.Text;
            set => TxtFavs.Text = value;
        }
        public string SearchTweet
        {
            get => SrchTweet.Text;
            set => SrchTweet.Text = value;
        }
        public NSIndexPath IndexPath
        {
            get;
            set;
        }
		public CustomTableViewCell (IntPtr handle) : base (handle)
		{
		}

        public CustomTableViewCell()
        {
        }
	}
}
