// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Threading;
using System.Threading.Tasks;
using ExamenP2_62453.Models;
using Foundation;
using UIKit;

namespace ExamenP2_62453
{
    public partial class TwitterViewController : UITableViewController, IUISearchResultsUpdating
    {
        #region Class Variables
        UISearchController searchController;
        Models.Twitter twitter;
        List<Tweet> tweets = new List<Tweet>();
        CancellationTokenSource cancellationTokenSource;
        #endregion
        #region Constructors
        public TwitterViewController(IntPtr handle) : base(handle)
        {
        }
        #endregion
        #region Life Cycle
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitializeComponents();


        }
        #endregion
        #region Table Data Source
        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell(CustomTableViewCell.Key, indexPath) as CustomTableViewCell;
            try
            {
                Contract.Ensures(Contract.Result<UITableViewCell>() != null);
                if (tweets.Count > 0)
                {


                    cell.Tweet = $"{tweets[indexPath.Row].Text}";
                    cell.ReTweet = $"{tweets[indexPath.Row].ReTweets}";
                    cell.Fav = $"{tweets[indexPath.Row].Favorite}";
                    cell.IndexPath = indexPath;

                }
                else
                {
                    
                }
                return cell;
            }catch(Exception ex)
            {
                cell.Tweet = "";
                cell.ReTweet = "";
                cell.Fav = "";
                cell.IndexPath = indexPath;
                return cell;
            }


        }
        public override nint RowsInSection(UITableView tableView, nint section)
        {
            try
            {
                return tweets.Count;
            }catch(Exception ex)
            {
                return 0;
            }
        }
        public override nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }
        #endregion
        #region User Interactions

        #endregion
        #region Internal Functionlality
        void InitializeComponents()
        {
            tweets = new List<Tweet>();
            searchController = new UISearchController(searchResultsController: null)
            {
                SearchResultsUpdater = this,
                DimsBackgroundDuringPresentation = false
            };
            twitter = new Models.Twitter();
            AuthorizeAsync();
            GetTweetsAsync("MTB XC");
            TableView.ReloadData();
            TableView.TableHeaderView = searchController.SearchBar;
            TableView.RowHeight = UITableView.AutomaticDimension;
            TableView.EstimatedRowHeight = 100f;
            searchController.SearchBar.SearchButtonClicked += SearchBar_SearchButtonClicked;

        }
        async void AuthorizeAsync()
        {
            await twitter.Authorize();
        }
        async void GetTweetsAsync(string query)
        {
            tweets = await twitter.GetTweets(query);
        }

        void SearchBar_SearchButtonClicked(object sender, EventArgs e)
        {
            if (searchController.SearchBar.Text != " ")
            {

                    GetTweetsAsync(searchController.SearchBar.Text);
                    TableView.ReloadData();
            }
        }
        void ShowGenericAlert(string title, string content)
        {
            var alert = UIAlertController.Create(title, content, UIAlertControllerStyle.Alert);
            alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));
            PresentViewController(alert, true, null);

        }

        public void UpdateSearchResultsForSearchController(UISearchController searchController)
        {
            
        }
        #endregion

    }
}
